### PR TITLE
Change attr readers to protected

### PR DESCRIPTION
**Pull request by ksarunas**
Does not really change anything, but feels better.

@laurynas @astrauka

### CODE REVIEW

**Comment by laurynas** [comment]
👍

**Comment by astrauka** [comment]
@ksarunas I avoid using `protected` in ruby as it does not mean the same as in normal languages like C and Java, so not sure if this change actually changes anything, but :+1:

**Comment by ksarunas** [comment]
> as in normal languages like C and Java

could you define what is normal? 😄 And is it a bad thing to be `not normal`? 😄

**Comment by astrauka** [comment]
@ksarunas `normal` in this case is intuitive when described with real world example :)

**Pull request merged**
